### ISSUE TITLE
1.1.3 release contains phishing(?) code.

### ISSUE THREAD

**Issue by chr0n1x** [TheoBr/Chrometana#27] opened 2017-06-17 16:33 UTC
Today, the plugin required new permissions to reactivate. When activated, going to **ANY** site resulted in a popup message saying that my computer is infected, and then it redirects the user to 

`https://chromeupdates.top/s.html` (DO NOT CLICK UNLESS YOU KNOW WHAT YOU'RE DOING)

Poking around that page I found this:
https://gist.github.com/chr0n1x/989af9702845cbd501fe51e897575dfe

Seems to just be a script that doesn't really do much (according to [this thread](https://www.reddit.com/r/Malware/comments/6dm5m2/the_infinity_new_tab_chrome_extension_appears_to/)). But still, concerning.

**Comment by The-MAZZTer** [comment] 2017-06-17 17:06
I can confirm. Either the author of the extension sold out his users, or his Google account was compromised.

The code does not seem to have been uploaded to github.

**Comment by chr0n1x** [comment] 2017-06-17 17:16
@The-MAZZTer can you gist `alert10.js` so we can take a look @ it?

**Comment by The-MAZZTer** [comment] 2017-06-17 17:57
https://www.dropbox.com/s/5l9prxit0y3ue7s/Chrometana%201.1.3%20%28ONLY%20FOR%20ANALYSIS%20MAY%20CONTAIN%20SPYWARE%20DO%20NOT%20INSTALL%20INTO%20CHROME%29.zip?dl=0

I looked at the manifest file. It looks like it may contain a workaround to prevent Google from automatically catching it.

`   "content_scripts": [ {
      "js": [ "alert10.js" ],
      "matches": [ "\u003Call_urls>" ],
      "run_at": "document_start"
   } ],`

This injects alert10.js into every page you visit (which I assumed it did).

I do lots of JS coding for a living so I figured I could do my own analysis.

First of all, it looks like most of the file from the start is an md5 JS library. However it appears to not be used at all

Line 193 appears to be where the author's code starts. When I break it down it appears to do the following:

1. Check the current page to see if it's a "keeper" page (I think this is a page on the site the user is ultimately redirected to).
2. Use a cookie called "_alert" to track the last time we showed a popup to the user. Only if it has been more than 10 seconds AND the current page is not a "keeper" page do we show a new alert.
3. Show a yes/no popup dialog with the message "Your computer is infected. You have to check it with antivirus.". However, show it in the user's native language if the user's language is Spanish, Italian, French, Portuguese, German, Russian, or Greek.
4. If the user clicks yes, redirect the current page to http : // chromeupdates . top / tds . php ? subid = ce Otherwise redirect the page to https : // chromeupdates . top / s . html (I DO NOT RECOMMEND VISITING THESE PAGES I DON'T KNOW WHAT IS ON THEM)

**Comment by Wazbat** [comment] 2017-06-17 18:54
Damn. It's scary to see something so trusted turn into this

**Comment by rossinimartins** [comment] 2017-06-17 18:55
Confirmed, happens here too.

Chrometana version 1.1.3 via Download Chrome Extension on Opera 45.

**Comment by hypernova1912** [comment] 2017-06-17 19:52
I will mention that this is the exact same thing that happened to Infinity New Tab, complete with the same wording, a month or two ago, so it's probably a compromised account.

**Comment by TheoBr** [comment] 2017-06-17 20:24
Hey guys! Fun fact. When your extension gets taken down due to a bullshit DMCA notice, it's possible for others to somehow push updates.

I am in contact with Google and will be putting up an official press release tonight. This is absolutely maddening and I'm so sorry guys.

**Comment by hypernova1912** [comment] 2017-06-17 20:25
Oh, and by the way, EdgeDeflector allows us to use Chrome with Cortana, so the extension has a purpose again. Yay!

**Comment by TheoBr** [comment] 2017-06-17 20:47
Google is not responsive and I have no idea how any of this happened. I'm shipping an update momentarily. If anyone has advice on how to get ahold of Google and fix/prevent garbage like this please let me know

**Comment by hypernova1912** [comment] 2017-06-17 20:50
The problem is that Google has _literally_ no customer support, other than specialized departments like the Pixel. I once had someone already have a Google account _with my email_ and nobody could help me get it removed.

**Comment by TheoBr** [comment] 2017-06-17 21:04
Update shipping soon

http://chrometana.theo.li/2017/06/google-account-compromised-malware-shipped-chrometana-1-1-3/

**Comment by TheoBr** [comment] 2017-06-17 21:16
Update has been shipped. I'm closing this for now, but please don't hesitate to contact me with anything at all

**Closed by TheoBr** 2017-06-17 21:16 UTC

**Comment by MissPotato** [comment] 2017-06-17 22:57
I'll be running the necessary test to hopefully insure that my PC is clean, however could we get a statement about the malwares' effect on end users who may not be able to read the code?

**Comment by TheoBr** [comment] 2017-06-17 23:04
@MissPotato , the "malware" included was a small javascript pop-up. That pop-up could bring you to a website with worse viruses. 

If you did not download anything from a suspicious webpage, you're fine.

**Comment by MissPotato** [comment] 2017-06-18 00:16
@TheoBr , thanks for the statement! I tend to avoid downloading things from sites I don't use.
